# Generated by Django 3.2.7 on 2021-10-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('humidity', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Weather_csv',
            },
        ),
    ]
